import { DairyCompany } from '@/types/dairy';

export const dairyCompanies: DairyCompany[] = [
  {
    id: 'amul',
    name: 'Amul',
    logo: '🥛',
    states: ['Gujarat', 'Maharashtra', 'Rajasthan', 'Madhya Pradesh', 'Delhi', 'Uttar Pradesh'],
    pricePerLiter: { cow: 42, buffalo: 52 },
    rating: 4.8,
    totalFarmers: 350000,
    paymentCycle: 'biweekly',
  },
  {
    id: 'mother-dairy',
    name: 'Mother Dairy',
    logo: '🐄',
    states: ['Delhi', 'Haryana', 'Punjab', 'Uttar Pradesh', 'Rajasthan'],
    pricePerLiter: { cow: 40, buffalo: 50 },
    rating: 4.6,
    totalFarmers: 180000,
    paymentCycle: 'weekly',
  },
  {
    id: 'dodla-dairy',
    name: 'Dodla Dairy',
    logo: '🌾',
    states: ['Andhra Pradesh', 'Telangana', 'Karnataka', 'Tamil Nadu', 'Maharashtra'],
    pricePerLiter: { cow: 38, buffalo: 48 },
    rating: 4.5,
    totalFarmers: 120000,
    paymentCycle: 'biweekly',
  },
  {
    id: 'sudha',
    name: 'Sudha',
    logo: '🏔️',
    states: ['Bihar', 'Jharkhand', 'West Bengal'],
    pricePerLiter: { cow: 36, buffalo: 46 },
    rating: 4.3,
    totalFarmers: 85000,
    paymentCycle: 'weekly',
  },
  {
    id: 'nandini',
    name: 'Nandini (KMF)',
    logo: '🌿',
    states: ['Karnataka'],
    pricePerLiter: { cow: 39, buffalo: 49 },
    rating: 4.7,
    totalFarmers: 240000,
    paymentCycle: 'biweekly',
  },
  {
    id: 'aavin',
    name: 'Aavin',
    logo: '🌴',
    states: ['Tamil Nadu'],
    pricePerLiter: { cow: 37, buffalo: 47 },
    rating: 4.4,
    totalFarmers: 95000,
    paymentCycle: 'weekly',
  },
  {
    id: 'milma',
    name: 'Milma',
    logo: '🥥',
    states: ['Kerala'],
    pricePerLiter: { cow: 41, buffalo: 51 },
    rating: 4.5,
    totalFarmers: 78000,
    paymentCycle: 'biweekly',
  },
  {
    id: 'verka',
    name: 'Verka',
    logo: '🌾',
    states: ['Punjab', 'Haryana', 'Chandigarh'],
    pricePerLiter: { cow: 43, buffalo: 53 },
    rating: 4.6,
    totalFarmers: 110000,
    paymentCycle: 'weekly',
  },
];

export const indianStates = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
  'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand',
  'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
  'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab',
  'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura',
  'Uttar Pradesh', 'Uttarakhand', 'West Bengal', 'Delhi', 'Chandigarh'
];
